apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  labels:
    type: local
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus"
  persistentVolumeReclaimPolicy: Retain
