adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

persistence:
  enabled: true
  size: 10Gi

# Basic datasource setup - assuming Prometheus is running in the cluster
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

# Set up default dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Default dashboards to include
dashboards:
  default:
    kubernetes:
      gnetId: 10000
      revision: 1
      datasource: Prometheus
